# Generated by Django 4.1.3 on 2023-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_link',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
